### ISSUE TITLE
Rewards don’t work at all

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/MonsterHunt#1]
This goes along with many recent tickets on dev.bukkit.org page – rewards are set up properly while they are just not dispensed to winners at all.

``` yaml
Rewards:
  RewardParametersPlace1: 331 16-32,20 16-32
  RewardParametersPlace2: 331 8-16,20 8-16
  RewardParametersPlace3: 331 4-8
  RewardParametersPlace4: 20 4-8
  RewardParametersPlace5: 20 2-4
  EnableReward: true
  EnableRewardEveryonePermission: false
  RewardEveryone: true
  MinimumPointsEveryone: 1
  NumberOFWinners: 5
  RewardParametersEveryone: 263:2 1
```

Translation for winners:
1. 16-32 redstone and 16-32 glass
2. 8-16 redstone and 8-16 glass
3. 4-8 redstone
4. 4-8 glass
5. 2-4 glass
6. Everyone else: 1 piece of charcoal
