### ISSUE TITLE
Multiple sets of rewards

### ISSUE THREAD

**Issue by eliadil** [CoreNetwork/MonsterHunt#16]
Right now reward specification looks like this : 

```
RewardParametersPlace1: 331 16-32,20 16-32
RewardParametersPlace2: 331 8-16,20 8-16
RewardParametersPlace3: 331 4-8
RewardParametersPlace4: 20 4-8
RewardParametersPlace5: 20 2-4
```

I would like to change that to multiple sets of RewardParameters. Each time Hunt starts, it would take random set of rewards. 

Additionally, every set specification should include weight parameter, to determine how often it will occur.

Example :

```
RewardSets: 
  - 
    Weigh: 50
    RewardParametersPlace1: 331 16-32,20 16-32
    RewardParametersPlace2: 331 8-16,20 8-16
    RewardParametersPlace3: 331 4-8
    RewardParametersPlace4: 20 4-8
    RewardParametersPlace5: 20 2-4
  - 
    Weight: 1
    RewardParametersPlace1: 42 64
    RewardParametersPlace2: 42 32
```
