### ISSUE TITLE
Damage value for items cannot exceed two digits

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/MonsterHunt#30]
It would seem.

Tried:

``` yaml
Rewards:
  EnableReward: true
  NumberOfWinners: 5
  EnableRewardEveryonePermission: false
  RewardEveryone: true
  MinimumPointsPlace1: 200
  RewardParametersPlace1: 5 373:8259
  MinimumPointsPlace2: 150
  RewardParametersPlace2: 3 373:8259
  MinimumPointsPlace3: 100
  RewardParametersPlace3: 1 373:8259,2 373:8227
  MinimumPointsPlace4: 75
  RewardParametersPlace4: 2 373:8227
  MinimumPointsPlace5: 50
  RewardParametersPlace5: 1 378
  MinimumPointsEveryone: 1
  RewardParametersEveryone: 263 1
```

For Fire Resist potions and it created a stream of errors.
