### ISSUE TITLE
Feature request: modify points depending on the enchant on weapon used

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/MonsterHunt#33]
`Sharpness V` is only available to endgame players. If a new player wants to have a shot at prizes, they will almost always use a lesser weapon. I think we need to create a more balanced playing field so that everyone can enjoy prizes, not only select few.

Ideally, it would be a penalty based on Enchantment and Level:

``` yaml
EnchantPenalty:
    - enchant:
        name: DAMAGE_ALL
        level: 5
        penalty: 5
    - enchant:
        name: DAMAGE_ALL
        level: 4
        penalty: 4
    - enchant:
        name: DAMAGE_ALL
        level: 3
        penalty: 3
    - enchant:
        name: DAMAGE_ALL
        level: 2
        penalty: 2
    - enchant:
        name: DAMAGE_ALL
        level: 1
        penalty: 1
    - enchant:
        name: KNOCKBACK
        level: 2
        penalty: 1
```

And so forth. Enchants can be human-readable or raw Bukkit names.
