### ISSUE TITLE
Add hunt instructions

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/MonsterHunt#51]
It would be a simple string node under this root node:

``` yaml
Hunts:
- Name: default
  Chance: 20
  DisplayName: 'Undead Hunt'
  Instructions: 'Kill Zombies with Golden Sword for 2 extra points. 
Kill Skeletons with a bone for extra point.'
```

Then a variable `<Instructions>` could be used in `MessageSignUpPeriod`:

``` yaml
MessageSignUpPeriod: '&aMonster Hunt will begin in 60 seconds! &6/hunt join &ato join. [NEWLINE]
 &6&l<DisplayName>&r&6''s &7twist: <Instructions> More: /help Hunt'
```

This would make sure people understand what is expected of them during the hunt.
