### ISSUE TITLE
What is MinimumPointsPlaceX?

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/MonsterHunt#7]
I studied documentation but I cannot really understand what

``` yaml
MinimumPointsPlace1: 30
MinimumPointsPlace2: 20
MinimumPointsPlace3: 10
MinimumPointsPlace4: 5
MinimumPointsPlace5: 2
```

does… is it like a global high score list, which is updated after every hunt?
